<?php 
session_start();
require('fpdf/fpdf.php');
$ACCES_INFORMATION_Ville = $_SESSION["ACCES_INFORMATION_Ville"];
$ACCES_INTERFACES_NUMERIQUES_Ville = $_SESSION["ACCES_INTERFACES_NUMERIQUES_Ville"];
$COMPETENCES_ADMINISTRATIVES_Ville = $_SESSION["COMPETENCES_ADMINISTRATIVES_Ville"];
$COMPETENCES_SCOLAIRES_Ville = $_SESSION["COMPETENCES_SCOLAIRES_Ville"];
$GLOBAL_ACCES_Ville = $_SESSION["GLOBAL_ACCES_Ville"];
$GLOBAL_COMPETENCES_Ville = $_SESSION["GLOBAL_COMPETENCES_Ville"];
$SCORE_GLOBAL_Ville = $_SESSION["SCORE_GLOBAL_Ville"];

$ACCES_INFORMATION_Dep = $_SESSION["ACCES_INFORMATION_Dep"];
$ACCES_INTERFACES_NUMERIQUES_Dep = $_SESSION["ACCES_INTERFACES_NUMERIQUES_Dep"];
$COMPETENCES_ADMINISTRATIVES_Dep = $_SESSION["COMPETENCES_ADMINISTRATIVES_Dep"];
$COMPETENCES_SCOLAIRES_Dep = $_SESSION["COMPETENCES_SCOLAIRES_Dep"];
$GLOBAL_ACCES_Dep = $_SESSION["GLOBAL_ACCES_Dep"];
$GLOBAL_COMPETENCES_Dep = $_SESSION["GLOBAL_COMPETENCES_Dep"];
$SCORE_GLOBAL_Dep = $_SESSION["SCORE_GLOBAL_Dep"];

$ACCES_INFORMATION_Reg = $_SESSION["ACCES_INFORMATION_Reg"];
$ACCES_INTERFACES_NUMERIQUES_Reg = $_SESSION["ACCES_INTERFACES_NUMERIQUES_Reg"];
$COMPETENCES_ADMINISTRATIVES_Reg = $_SESSION["COMPETENCES_ADMINISTRATIVES_Reg"];
$COMPETENCES_SCOLAIRES_Reg = $_SESSION["COMPETENCES_SCOLAIRES_Reg"];
$GLOBAL_ACCES_Reg = $_SESSION["GLOBAL_ACCES_Reg"];
$GLOBAL_COMPETENCES_Reg = $_SESSION["GLOBAL_COMPETENCES_Reg"];
$SCORE_GLOBAL_Reg = $_SESSION["SCORE_GLOBAL_Reg"];

$pdf = new FPDF("P","pt","A4");
$pdf->AddPage();
$pdf->SetFont('Arial','',12);
$pdf->Cell(0,0,$ACCES_INFORMATION_Ville);
$pdf->Cell(0,0,$ACCES_INTERFACES_NUMERIQUES_Ville);
$pdf->Cell(0,0,$COMPETENCES_ADMINISTRATIVES_Ville);
$pdf->Cell(0,0,$COMPETENCES_SCOLAIRES_Ville);
$pdf->Cell(0,0,$GLOBAL_ACCES_Ville);
$pdf->Cell(0,0,$GLOBAL_COMPETENCES_Ville);
$pdf->Cell(0,0,$SCORE_GLOBAL_Ville);

$pdf->Cell(0,0,$ACCES_INFORMATION_Dep);
$pdf->Cell(0,0,$ACCES_INTERFACES_NUMERIQUES_Dep);
$pdf->Cell(0,0,$COMPETENCES_ADMINISTRATIVES_Dep);
$pdf->Cell(0,0,$COMPETENCES_SCOLAIRES_Dep);
$pdf->Cell(0,0,$GLOBAL_ACCES_Dep);
$pdf->Cell(0,0,$GLOBAL_COMPETENCES_Dep);
$pdf->Cell(0,0,$SCORE_GLOBAL_Dep);

$pdf->Cell(0,0,$ACCES_INFORMATION_Reg);
$pdf->Cell(0,0,$ACCES_INTERFACES_NUMERIQUES_Reg);
$pdf->Cell(0,0,$COMPETENCES_ADMINISTRATIVES_Reg);
$pdf->Cell(0,0,$COMPETENCES_SCOLAIRES_Reg);
$pdf->Cell(0,0,$GLOBAL_ACCES_Reg);
$pdf->Cell(0,0,$GLOBAL_COMPETENCES_Reg);
$pdf->Cell(0,0,$SCORE_GLOBAL_Reg);
$pdf->Output();
?>